### ISSUE TITLE
[RepCode] Extend RepetitionQubit from XXZZQubit

### ISSUE THREAD

**Issue by amirebrahimi** [yaleqc/qtcodes#60]
Extend `RepetitionQubit` from `XXZZQubit` (or at least `RotatedQubit`), as the Repetition code can be thought of as a very slim surface code. This would follow the work from #27 and #28.

Add a `RepetitionPhaseQubit` as well as a "row" repetition code.

**Comment by Phionx** [comment]
Closed by #69.
